# Generated by Django 4.2.30 on 2026-10-01 22:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bicicletas', '0008_modelo_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemventa',
            name='bicicleta',
        ),
        migrations.RemoveField(
            model_name='itemventa',
            name='venta',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='cliente',
        ),
        migrations.AlterField(
            model_name='bicicleta',
            name='precio',
            field=models.DecimalField(decimal_places=0, max_digits=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000000)]),
        ),
        migrations.AlterField(
            model_name='bicicleta',
            name='precio_oferta',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000000)]),
        ),
        migrations.DeleteModel(
            name='CarritoItem',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='ItemVenta',
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
